import { signOut } from 'next-auth/react';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button
          onClick={() => {
            signOut();
          }}
        >
          Sign Out
        </button>
      </main>
    </div>
  );
}
