import { signOut } from 'next-auth/react';
import Head from 'next/head';
import Header from '../components/header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <button
        onClick={() => {
          signOut();
        }}
      >
        Sign Out
      </button>
      <main className=""></main>
    </div>
  );
}
